name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master # 当推送到 main 分支时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 使用最新 Ubuntu 运行环境

    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 指定 Node.js 版本

      # 安装 Angular CLI
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # 安装依赖
      - name: Install project dependencies
        run: npm install

      - name: Build Angular app
        run: ng build --base-href "/${{ github.event.repository.name }}/" --output-path=dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
